### ISSUE TITLE
Unbricking JMS567

### ISSUE THREAD

**Issue by Massimo-B** [projectgus/jms567ctl#4]
Hi,

I have a Orico DS500U3 device using a JMS567.
It reported itself as:
```
Bus 003 Device 003: ID 152d:0567 JMicron Technology Corp. / JMicron USA Technology Corp. JMS567 SATA 6Gb/s bridge
```
It should support UAS but was not according to lsusb -v.
Now I just tried flashing a firmware from
https://www.station-drivers.com/index.php/en/component/remository/Drivers/Jmicron/JMS567-Sata-USB-3.0-Controller/Jmicron-JMS-567-Firmware-Version-20.06.00.01/lang,en-gb/
After a device restart, no entry in the syslogs and nothing in lsusb, just dead.

Too bad, I found your project just after that. How can I unbrick it? You describe I need to short the flash chip CS pin to ground, where do I find this?

**Comment by Massimo-B** [comment]
I found 2 flash chips "fm25f01". Pin 1 (marked) is CS, Pin 4 is VSS (Ground). So I tried a shortcut from 1 to 4 and started the device. Some seconds after starting I remove the shortcut. 
Because I don't know which of the 2 flash chips is the custom firmware, I tried that shortcut on both chips.
But the device does not show up via USB, nothing in lsusb or kernel log.

**Comment by projectgus** [comment]
Hi @Massimo-B,

What you've done is what other people reported working (assuming that "started the device" means "powered on"). If there's two flash chips then there must be some additional logic in this product, though, so maybe that is the extra difference/complexity.

If you have a detailed photo of the board then I'd be happy to see if I can suggest anything else, but it sounds like it might be properly dead from the first update. :grimacing:

**Comment by Massimo-B** [comment]
![IMG_20240403_072838 HEIC](https://github.com/projectgus/jms567ctl/assets/3286728/96cb35c5-fe43-4809-aa52-e0cd2c1cf12f)
![IMG_20240403_105018 HEIC](https://github.com/projectgus/jms567ctl/assets/3286728/8c36c37a-00d7-49a7-a80f-373c9ee52a1a)
![IMG_20240403_105040 HEIC](https://github.com/projectgus/jms567ctl/assets/3286728/25d3a549-8ba9-4709-bc45-6aafd619213f)

**Comment by Massimo-B** [comment]
With "started" I mean, I tried pressing the power button and also re-plugging power. Both seem to be the same as Pin 1 to Pin 4 are getting about ~~3 Volt~~ -3 Volt when pressing the power button and are without voltage when pressing again.
I felt a bit uncertain to short that voltage, but there was only little mA going.

Specs of that flash memory:
https://www.fmsh.com/nvm/FM25F01_ds_eng.pdf

So short Pin 1 and 4 should make it failing to read, falling back to the rom basic firmware, and any of these 2 chips should be the right one?

**Comment by Massimo-B** [comment]
I need to correct... Pin 1 to 4 gets -3V.

**Comment by Massimo-B** [comment]
Just for understanding, in order to be able to flash via USB, there must appear any new device in the kernel log or in lsusb? I'm just watching the syslog when doing these restarts.
When the rom firmware gets started, then it should report itself as some device via USB?

**Comment by projectgus** [comment]
Interesting! U14 is the JMS567 USB/SATA adapter, so its flash chip is going to be the nearby U2. The other chip U10 is a JMB575 SATA port multiplier chip, and it looks like it has its own associated flash as well.

Just to check, pin 1 is the bottom right in these photos so you shorted across like this, yes?

![image](https://github.com/projectgus/jms567ctl/assets/205573/c403e757-71d0-4adf-b5ac-9777c33fd8b0)

> So short Pin 1 and 4 should make it failing to read, falling back to the rom basic firmware, and any of these 2 chips should be the right one?

That's right. Pin 1 should be at 3.3V normally, relative to pin 4 (ground). The JMS567 chip will toggle pin 1 (CS) down to 0V each time it talks to the flash to read (or write, etc). If you short them together then the commands will not be parsed correctly and the data likely gets corrupted to the JMS567, causing it to fall back. At least this is the theory. Best to use a piece of wire or something with very low resistance to do this.

> When the rom firmware gets started, then it should report itself as some device via USB?

Yes, that's right. It seems like it fails to boot from the flash then it falls back to an image in ROM. Maybe that's not true for every revision of JMS567, though...

**Comment by projectgus** [comment]
Also, just to check, in the photos there's something that looks kind of like solder paste on U2's pins including maybe between pins 4 and 3?

**Comment by Massimo-B** [comment]
I've seen that solder, but it was working before I flashed that broken firmware. But I can check if that's an issue...
Yes, I did the shortening like you showed in the picture. But that Pin 1 here has a negative -3V to Pin 4, is that correct?

**Comment by Massimo-B** [comment]
Usually I do the shortening via an Amperemeter of 250mA, but I also tried with a direct connection.
I perfectly see the -3V when starting, so I have a good connection.
How long does the JMS567 toggle down to 0V, just some milli seconds? I don't see this step with a simple voltmeter.

**Comment by Massimo-B** [comment]
If I would go for another device of that type, it's still unclear to me, if there is a working firmware that support UAS. On the (chinese) packaging there is written "UASP". But according to lsusb -vv and also on Windows, no UAS was offered by that firmware and I appearently bricked if by just flashing some untrusted firmware..

**Comment by Massimo-B** [comment]
I got support from https://www.mikrocontroller.net . The device is back to live.
It was wrong to short the CS to GND (VSS), it must be connected to Power (VCC), so Pin 1 to Pin 8. Then it was wrong that I've taken the color-marked Pin as 1. This was Pin 4 as there is a notch for the real Pin 1.

Now the device is back on USB. Please adapt that in your main wiki.

Now I'm back to the origin question: Which firmware should I take for UAS?
The good is I can just try around some untrusted firmwares and always fall back to the rom firmware if failing.

Instead of using all the unknown flashing software from a Windows VM, I would prefer your flash software here. Is there a trustful place to get firmwares from?

**Comment by projectgus** [comment]
> I got support from https://www.mikrocontroller.net . The device is back to live. 

Very glad to hear that. 

> It was wrong to short the CS to GND (VSS), it must be connected to Power (VCC), so Pin 1 to Pin 8. Then it was wrong that > I've taken the color-marked Pin as 1. This was Pin 4 as there is a notch for the real Pin 1.
> 
> Now the device is back on USB. Please adapt that in your main wiki.

That's interesting. I would have expected shorting CS to either VCC or GND would work much the same (in the first case no SPI flash command can be sent at all, in the second case the first SPI flash command never completes and everything after it should read junk data). Previously I've had one report of CS to GND working, I never actually tried it myself.

To make very sure: can you please confirm that you did try shorting pins 1 and 4 as marked in the photo above, using a short piece of wire (not a multimeter or some other device), and that didn't work?

> Now I'm back to the origin question: Which firmware should I take for UAS? The good is I can just try around some untrusted firmwares and always fall back to the rom firmware if failing.

Mate, I don't know. I don't work for Orico or JMicron, I'm just a person who posted an experimental tool on the internet.

The firmwares are technically copyrighted by one of those companies, which is why I don't post them here (although probably no one would care). I think if you search online you will find some discussion about which firmware(s) work best on some devices, I'm not sure about your particular device though.

**Comment by projectgus** [comment]
> The firmwares are technically copyrighted by one of those companies, which is why I don't post them here (although probably no one would care).

I've added a table with some known "unofficial" firmware combos that work:

https://github.com/projectgus/jms567ctl#firmware

Unfortunately it looks like the one that worked for mine is the one that bricked yours. :shrug:

**Comment by IceReaper** [comment]
I have the same chip, in an icy box ib-rd3621u3. Device boots up, but not visible via usb. Im currently running windows, but if this is linux-only, i can boot a linux too.
So if i understand this correctly:
- device off
- short pin 1 (with the notch) with 8 (the one furthest away from the notch)
- device on and wait for it to show up as usb device
- remove the short when it fully booted
- flash firmware with this tool
- done?

**Comment by projectgus** [comment]
@IceReaper You've got it. I actually just went through this process with a JMS577 two days ago!

I've personally had more success shorting CS to GND as shown here:

![qspi_nor_soic8_pinout_qspi](https://github.com/user-attachments/assets/af6f3bf5-bb3a-43dd-8077-7a70e5eed02b)
![PXL_20240728_235105352](https://github.com/user-attachments/assets/ce1a5689-b6d7-454e-9550-2a7ebbd66789)
![PXL_20240728_235309012](https://github.com/user-attachments/assets/3393af12-cdf4-4d8e-98e3-05e1bcbb5976)

However @Massimo-B found they needed to short CS to VCC. Either way the goal is to disrupt the SPI flash commands enough that the chip can't boot its normal firmware and fails back to the internal Mask ROM firmware.

However, I also recently discovered a tool called jms578flash: https://github.com/BertoldVdb/jms578flash

I missed this when I was making jms567ctl. It seems like jms578flash works with all of this JMicron series (might need to pass `-device 0xVID:0xPID` command line argument). It's also more advanced - can write the flash in situations where it didn't always work for me, and can even reset the chip without needing any of these shorting tricks. I'm probably going to mark this repo as Archived soon and link to jms578flash as a better alternative - so you might want to look into it instead.

**Comment by maxdec** [comment]
Hi, you guys just saved my 7 years old Orico enclosure! Thank you so much!!

I had bricked it by trying to flash some (random?) firmware. I got an "SCSI error" during the write. Then it couldn't start properly anymore (was doing one bip when booting, but wasn't showing up in `lsblk` nor in `lsusb` and only the first bay was lit).

I managed to make it show up by shorting the pins 1-4 and re-flash the original firmware. Now everything works fine.

During the process I did try https://github.com/BertoldVdb/jms578flash but it didn't want to flash any JMS567 firmwares, saying that the bin files were the wrong size, or too short. So please do not archive your tool yet, it's still helpful! :)

**Comment by Massimo-B** [comment]
Very interesting. As I wrote I managed to get the JMS567 into flashing mode, but I didn't make progress yet as I don't have the right firmware. My Orico enclosure is a 5-bay enclosure for 5 SATA drives. Maybe the firmware is just identical to any other of the Orico enclosures. **Where did you get your firmware from?** You like to share?
Originally I started flashing around, as the original firmware did not support UAS eventhough the hardware was advertised to support that. Without UAS the performance was poor, especially when running all 5 discs as a software raid with mdadm.

Now that we get the device forced into flashing mode by shorting the pins, is it safe to try arbitrary firmwares? If a firmware doesn't match I can always re-flash or could the internal mask firmware be damaged by that?

**Comment by maxdec** [comment]
I've got an old Orico 9548RU3. It's 4-bay but it actually has 5 sata slots internally, and I did put 5 disks in there. The last one is just hidden, so it may be similar to yours.

Luckily I had taken a backup of my original firmware, so that's the one I restored. I tried 2 other firmwares from https://www.usbdev.ru/files/jmicron/jms567firmware/ but none worked (`JMS567_ORICO_UASP_v100.1.0.0-2013.12.21.BIN` and `JMS567_SSI_v20.06.00.01.bin`).

I can send my default firmware to you if you want. According to the tool, the firmware version was `0.3.2.3`, fwiw.

**Comment by Craig-Powell** [comment]
> During the process I did try https://github.com/BertoldVdb/jms578flash but it didn't want to flash any JMS567 firmwares, saying that the bin files were the wrong size, or too short. So please do not archive your tool yet, it's still helpful! :)

That utility could be similar to flashrom, where it expects the bin to be the same size as the chip.  I've been playing around with my [Orico 9558U3](https://www.orico.cc/us/product/detail/6775.html) with the rom chip in a ZIF socket.  Flashrom was telling me the flash was the wrong size until I padded the bin out to the size of the rom chip.  For the FM25Q04 I was working with this was 512K, which I accomplished with the command `truncate -s 512K romfile.bin`.  The truncate command actually works both directions it seems.  I guess maybe a program with more basic flash instruction will just check "does bin = rom size?" and if the answer is no then it will refuse to flash.  For as much as flashrom does I'm surprised I couldn't find an override switch to just ignore if the new bin was smaller than the chip size.

Side note, I've found a handful of firmware images that will "work" on the 9558U3, but only show one drive.  I guess they're for solo disk devices and don't need/have the multiplexer code.

**Comment by Massimo-B** [comment]
I would like to get all these firmwares you tried, to find the best firmware supporting by Orico 5-bay AND supporting UAS.
Is there any licensing issue to have a folder on this project collecting some of these firmwares? Could we just try? Alternatively we could start a collection of URLs to known firmwares in the Wiki?

**Comment by Craig-Powell** [comment]
Per Angus @projectgus  (I assume, I didn't look back through the commits to readme.md)...

> Because the firmware binaries themselves are intellectual property of JMicron and/or the product vendor, they're not distributed here.

And I would respect that.  But, I believe I recorded all the links of where I downloaded the fimreware files.  Give me some time to get organized and I can share the links.  I would think that should be acceptable.

**Comment by projectgus** [comment]
Yes, I wrote that. I think having a resource somewhere with all known firmware binaries would be very valuable (especially if it wasn't on some shady Russian website like a lot of the current options). However I don't want to host any binaries or even a list of firmware binary links here (even though I suspect the vendors don't really care.).

If you set up a web site or page somewhere else with a list of firmware then I don't mind linking to it as a possible resource, though.

**Comment by Craig-Powell** [comment]
Just got some momentary switches delivered and will be wiring one up to my Orico 9558U3.  Going to find out what works (GND or VCC to CS) for me to get the device to boot to the mask ROM so I can always recover from a bad flash via USB.  Hoping this works so I don't need to keep pulling the chip and flashing via an RPi and flashrom to recover.  After this I'll be going through the firmware images I have collected, getting hashes for each, and trying to see what does/doesn't work with notes on what level of success.  At minimum I'll put a table here (I believe I can do that in Markdown) with all that info.  While it won't be hosting the files it will give everyone the info to validate if downloads they've found match up and should be "safe" to try in their device.

I've got a lot of irons in the fire and organization is not my strong suit... please be patient with me in getting the firmware table/list together!

**Comment by icegood** [comment]
Hello. Great topic to discuss. I have Orico model as well (9558U3). 

And (of course :) ) I bricked my one as well. And I would like to unbrick it via short-circuiting CS to VCC via multimeters continuity mode. But it is hard to do 'on-premise' i.e. inside Orico. 
 
What I don't like about them pcb is that it seems to be power supplied from outside via a PCIe x4 interface, instead of USB. Who knows a better suitable setup?

**Comment by icegood** [comment]
Strange, i did everything as expected. Unplugged connector once device started. Controller detected

> ice@ice-home:jms567ctl:19982_8$ lsusb 
> Bus 002 Device 003: ID 152d:0569 JMicron Technology Corp. / JMicron USA Technology Corp. USB to ATA/ATAPI Bridge
> 

 but:
sudo env/bin/python3 jms567ctl.py -d 152d:0569 erase_flash

> 
> Traceback (most recent call last):
>   File "/home/ice/Documents/hardware/JMS567_orico_chip/jms567_main_controller/jms567ctl/jms567ctl.py", line 388, in <module>
>     main()
>   File "/home/ice/Documents/hardware/JMS567_orico_chip/jms567_main_controller/jms567ctl/jms567ctl.py", line 331, in main
>     cmd = USBCommander(vid, pid)
>           ^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/ice/Documents/hardware/JMS567_orico_chip/jms567_main_controller/jms567ctl/jms567ctl.py", line 80, in __init__
>     dev.set_configuration()  # set first configuration
>     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/ice/Documents/hardware/JMS567_orico_chip/jms567_main_controller/jms567ctl/env/lib/python3.12/site-packages/usb/core.py", line 929, in set_configuration
>     self._ctx.managed_set_configuration(self, configuration)
>   File "/home/ice/Documents/hardware/JMS567_orico_chip/jms567_main_controller/jms567ctl/env/lib/python3.12/site-packages/usb/core.py", line 113, in wrapper
>     return f(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/ice/Documents/hardware/JMS567_orico_chip/jms567_main_controller/jms567ctl/env/lib/python3.12/site-packages/usb/core.py", line 160, in managed_set_configuration
>     self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
>   File "/home/ice/Documents/hardware/JMS567_orico_chip/jms567_main_controller/jms567ctl/env/lib/python3.12/site-packages/usb/backend/libusb1.py", line 816, in set_configuration
>     _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
>   File "/home/ice/Documents/hardware/JMS567_orico_chip/jms567_main_controller/jms567ctl/env/lib/python3.12/site-packages/usb/backend/libusb1.py", line 604, in _check
>     raise USBError(_strerror(ret), ret, _libusb_errno[ret])
> usb.core.USBError: [Errno 16] Resource busy

**Comment by icegood** [comment]
Found reason:

works only via /dev/sda. Via 152d:0569 resource busy

**Comment by icegood** [comment]
Regarding my previous two comments: i didn't pay attention that **pyusb** backend is experimental.  


Regarding my tries with all possible firmwares in the internet: they either brick device or the only one out of 4 bays is reachable (in random manner, depend on power session only). 
Could someone please share original firmware for  Orico 9548U3?

Orico official is strange: they think that 9548U3 is supposed to be under JMS539B chip:
https://www.orico.cc/us/download.html?skeyword=9558


It is not my case thought! I definitely have JMS567/JMB575 pair

**Comment by maxdec** [comment]
@icegood This is the original firmware from my 9548RU3 (JMS567): https://maxdec.fr/default_firmware_orico_0.3.2.3.bin

**Comment by icegood** [comment]
hmm.. my one is not 9548RU3 but simply 9548U3. Will try anyway, thanks

**Comment by icegood** [comment]
> [@icegood](https://github.com/icegood) This is the original firmware from my 9548RU3 (JMS567): https://maxdec.fr/default_firmware_orico_0.3.2.3.bin

@maxdec nope, brick for me

**Comment by mateusz-kolecki** [comment]
Hi, I also have a 9558U3 and it is bricked.
I found this: https://www.orico.cc/usmobile/download.html?page=4.
Have someone tried this one?

**Comment by mateusz-kolecki** [comment]
On this official ORICO page https://www.orico.cc/us/download.html?skeyword=9558 (after typing "9558" in the search bar) there are two results with two links. It looks like something was messed up by the person who was publishing those files.

The link that says `9558U3` is supported contains a file that seems to be for `JMS539B` and the one that says to support `9558RU3` (pay attention to an additional `R` in the model name) seems to be for `JMS567`.

From what I learned so far it looks like `9558U3` should have `JMS567` inside.
I have no idea what sits in `9558RU3`.


It looks like you are far more competent in verifying if one of those files actually work with `9558U3`.

**Comment by mateusz-kolecki** [comment]
@icegood For some reason I skipped over your comment with the same link I posted. Sorry for not paying attention. Have you tried the other file under `9558RU3` model if it works with `9558U3`? The link is https://oos.oricogroup.com/JMS567.rar

**Comment by Craig-Powell** [comment]
It looks like the 9558RU3 uses the JMS539B based on this review:
https://goughlui.com/2015/11/01/review-orico-usb-3-0-5-bay-raid-hdd-enclosure-9558ru3-part-2/

**Comment by icegood** [comment]
> [@icegood](https://github.com/icegood) For some reason I skipped over your comment with the same link I posted. Sorry for not paying attention. Have you tried the other file under `9558RU3` model if it works with `9558U3`? The link is https://oos.oricogroup.com/JMS567.rar

Yes, i did. Desn't work as well. Basically, i had conversation with orico regarding them mess in web with no useful conclusions thought :( 
However, the one thing i could suspect: they mention that previous 'bad' firmware could break smth else. And i think is it connected to fact that some version might override firmware for JMB575 bridge as well? At least i don't understand why JMB575 has own external memory as well as was already mentioned above

**Comment by Massimo-B** [comment]
How did you get in contact with Orico? I really never got any reply from them.

**Comment by mateusz-kolecki** [comment]
I found some working firmware for `9558U3` on the Chinese Orico website. It looks like the Chinese version of the webpage is not just a translation but it is a totally different content.

1. go to https://www.orico.com.cn/download.html?skeyword=95%20%E7%B3%BB%E5%88%97
2. download button is the one with blue color and "下载" text on it (translator helps here)

Inside the archive you will find more zip files and one works with my `9558U3` 5 bay HDD enclosure.

The file name: `567B Orico PM v100.5.2.0.BIN`
SHA256: `5e089c61219782837c87696bb62a6b1a77a6e88a3f582d15fb36086b90e89b6c`

If the link does not work, try to search for this: "95 系列" using the search bar.

**Comment by icegood** [comment]
@mateusz-kolecki , you are hero! It works for me as well! 
Now we know what to suggest to orico - learn english or hire you :)

**Comment by icegood** [comment]
> How did you get in contact with Orico? I really never got any reply from them.

have no idea how but had a couple of ones from 
ORICO Official <supports@orico.com.cn>

**Comment by equake** [comment]
> 1. go to https://www.orico.com.cn/download.html?skeyword=95%20%E7%B3%BB%E5%88%97
> 2. download button is the one with blue color and "下载" text on it (translator helps here)

the download page does not exist anymore 🤔

**Comment by evert** [comment]
FYI i have a 5-bay yottamaster enclosure with a JMS567 and the firmware also bricked this device, so will try to see if I can unbrick it

**Comment by Massimo-B** [comment]
Unbricking by following the description above was no problem but I'm still looking for the right Firmware enabling UASP.

**Comment by evert** [comment]
Update: tried to unbrick, created a small flame on one of the ICs lol

**Comment by p-fruck** [comment]
I experienced the same issues mentioned in this thread, even though I used the same IcyBox model mentioned in the readme (Icybox IB-3640SU3, or at least I thought so). Unbricking worked for me as well using the microntroller.net instructions (not the ones that worked for icybox initially - Maybe I got some different kind of hardware revision?)!
I bricked and restored the device some months ago and got tired because I didn't find a matching firmware. Today I tried again. Apparently, JMS-567 Firmware Version 142.02.00.01 spawned on station-drivers in August. I flashed it and - it worked! My device reports `Driver=uas` in the `lsusb -t` output!
sha256sum: `c0774c11c9f4a2cd01b8ce1573beccfdba14b1d76b714733c378f272e45771a8  JMS567-CE-704U3-Release-v142.02.00.01-20240509.bin`

**Comment by mateusz-kolecki** [comment]
> > 1. go to https://www.orico.com.cn/download.html?skeyword=95%20%E7%B3%BB%E5%88%97
> > 2. download button is the one with blue color and "下载" text on it (translator helps here)
> 
> the download page does not exist anymore 🤔

@equake Try using web.archive.org:
https://web.archive.org/web/20250411005620/https://www.orico.com.cn/download.html

**Comment by Massimo-B** [comment]
> sha256sum: `c0774c11c9f4a2cd01b8ce1573beccfdba14b1d76b714733c378f272e45771a8 JMS567-CE-704U3-Release-v142.02.00.01-20240509.bin`

I googled that firmware, found it on some .ru page, sha256sum matches. So your Icybox IB-3640SU3 has 4 SATA docks, but identical JMS567 chipset and you got uas working with that fw? I'm going to try soon.

**Comment by p-fruck** [comment]
> So your Icybox IB-3640SU3 has 4 SATA docks, but identical JMS567 chipset and you got uas working with that fw?

Apparently yes
